### ISSUE TITLE
Quantile Normalise Avg.bigwig

### ISSUE THREAD

**Issue by Al-Murphy** [GuanLab/Leopard#8]
Hi,

I have downloaded the avg.bigwig file to use it to derive the 6th channel as input for training my model. I have quantile normalised my other Dnase-seq input data for the samples, is it necessary to quantile normalise the avg.bigwig file before use?

Thanks,
Alan.

**Comment by Hongyang449** [comment]
Hi Alan,

It depends on the reference file used during quantile normalization:
 you quantile normalized DNase-seq data:
(1) If you used the same reference (we used the liver data as the reference in this study), then you can directly use the avg.bigwig file. 
(2) If you used a different reference, I suggest you to create an avg.bigwig based on your own data instead of quantile normalizing the avg.bigwig. To create the avg.bigwig, you can simply calculate the average of all your DNase-seq data.

Thanks,
Hongyang

**Comment by Al-Murphy** [comment]
Perfect, thanks!
